# Generated by Django 4.2.13 on 2026-05-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='pdf',
            field=models.FileField(blank=True, help_text='Upload PDF file', null=True, upload_to='study/pdfs/'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, help_text='Upload general file (PDF or text file)', null=True, upload_to='study/materials/'),
        ),
    ]
