# Generated by Django 4.2.13 on 2026-05-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_studymaterial_pdf_alter_studymaterial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
