services:
  hartbeat-redis:
    container_name: hartbeat-redis
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - hartbeat-network

  hartbeat-backend:
    container_name: hartbeat-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://hartbeat-redis:6379/0
    depends_on:
      - hartbeat-redis
    restart: unless-stopped
    networks:
      - hartbeat-network
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  hartbeat-frontend:
    container_name: hartbeat-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - hartbeat-network

  hartbeat-nginx:
    container_name: hartbeat-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    depends_on:
      - hartbeat-backend
      - hartbeat-frontend
    restart: unless-stopped
    networks:
      - hartbeat-network

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  hartbeat-network:
    driver: bridge
