# Generated by Django 4.2.13 on 2026-05-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='community/messages/'),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
