# Generated by Django 4.2.13 on 2026-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_directmessage_file_directmessage_message_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='message_type',
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(),
        ),
    ]
