# Generated by Django 4.2.13 on 2026-06-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_directmessage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('file', 'File')], db_index=True, default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
