# Generated by Django 4.2.13 on 2026-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_communitymessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communitymessage',
            index=models.Index(fields=['-created_at'], name='community_m_created_898b71_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender', 'receiver', '-created_at'], name='direct_mess_sender__62b309_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['receiver', 'is_read'], name='direct_mess_receive_314ff8_idx'),
        ),
    ]
