# Generated by Django 4.2.13 on 2026-05-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supportcontact_created_at_supportcontact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportcontact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supportcontact',
            name='name',
        ),
        migrations.DeleteModel(
            name='MediaUpload',
        ),
    ]
