# Generated by Django 4.2.13 on 2026-05-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='habits.category')),
            ],
            options={
                'db_table': 'habit_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
