# Generated by Django 4.2.13 on 2026-05-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habittemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Scheduled time to perform this habit (e.g., 08:00)', null=True),
        ),
    ]
