# Generated by Django 4.2.13 on 2026-05-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_add_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
