# Generated by Django 4.2.13 on 2026-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habitmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmaterial',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='habitmaterial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='habitmaterial',
            name='file',
        ),
        migrations.AlterField(
            model_name='habitmaterial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video Link')], default='pdf', max_length=10),
        ),
    ]
