# Generated by Django 4.2.13 on 2026-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_remove_habitmaterial_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmaterial',
            name='video',
            field=models.FileField(blank=True, help_text='Upload Video file', null=True, upload_to='habits/videos/'),
        ),
    ]
