# Generated by Django 4.2.13 on 2026-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_habitmaterial_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmaterial',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='habitmaterial',
            name='video',
        ),
        migrations.AddField(
            model_name='habitmaterial',
            name='file',
            field=models.FileField(blank=True, help_text='Upload material file (PDF or Video)', null=True, upload_to='habits/materials/'),
        ),
    ]
