# Generated by Django 4.2.13 on 2026-06-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_habitmaterial_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='habitmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='habitmaterial',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='habitmaterial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video Link')], db_index=True, default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='habittemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='habittemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
