# Generated by Django 4.2.13 on 2026-06-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0012_alter_category_is_active_alter_habit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmaterial',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='habits.habittemplate'),
        ),
        migrations.AlterField(
            model_name='habitmaterial',
            name='habit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='habits.habit'),
        ),
        migrations.CreateModel(
            name='TemplateCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(help_text='Calendar date of completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habittemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_completions',
                'ordering': ['-completed_date', '-created_at'],
                'unique_together': {('user', 'template', 'completed_date')},
            },
        ),
    ]
