# Generated by Django 4.2.13 on 2026-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_add_template_completion_and_template_material'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['is_active', '-created_at'], name='habits_is_acti_abda78_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_active'], name='habits_user_id_41ce3a_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['user', 'completed_date'], name='habit_compl_user_id_48979b_idx'),
        ),
    ]
