# Generated by Django 4.2.13 on 2026-05-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_question_option_c_alter_question_option_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.studytopic'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study.studytopic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, help_text='Optional: legacy quiz grouping (deprecated)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, help_text='Optional: legacy quiz reference (deprecated)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study.quiz'),
        ),
    ]
