# Generated by Django 4.2.13 on 2026-06-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_question_topic_quizattempt_topic_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
