# Generated by Django 4.2.13 on 2026-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_question_order_alter_quiz_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active', 'is_selected'], name='quizzes_is_acti_56ea39_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz', '-completed_at'], name='quiz_attemp_user_id_2bcf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'topic', '-completed_at'], name='quiz_attemp_user_id_0580c9_idx'),
        ),
    ]
