# Generated by Django 4.2.13 on 2026-06-17 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('product_id', models.CharField(max_length=255)),
                ('purchase_type', models.CharField(choices=[('subscription', 'Subscription'), ('lifetime', 'Lifetime')], max_length=12)),
                ('original_transaction_id', models.CharField(max_length=255, unique=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('purchase_date', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('environment', models.CharField(default='Production', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iap_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iap_purchases',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
