# Generated by Django 4.2.13 on 2026-09-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0002_purchase_token_raw_resp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inapppurchase',
            new_name='iap_purchas_user_id_3fa1a0_idx',
            old_name='iap_purchas_user_id_30c024_idx',
        ),
    ]
