# Generated by Django 4.2.13 on 2026-05-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_alter_mood_svg_to_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='emoji',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
