# Generated by Django 4.2.13 on 2026-06-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0005_mood_svg_upload_path_to_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='heart_balance_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='mood',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
