# Generated by Django 4.2.13 on 2026-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0006_alter_checkin_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', '-created_at'], name='checkins_user_id_7cddfc_idx'),
        ),
    ]
