# Generated by Django 4.2.13 on 2026-05-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_password_reset_new_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='check_ins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_test',
            field=models.IntegerField(default=0),
        ),
    ]
